fix = false
target-version = "py312"

[lint]
select = ["ALL"]

ignore = [
    # Rule groups to ignore
    "D",   # pydocstyle
    "ANN", # flake8-annotations

    # The following rules may cause conflicts when used with the formatter
    "COM812",
    "ISC001",

    "ARG002",  # Unused method argument: `sender`
    "B905",    # [*] `zip()` without an explicit `strict=` parameter
    "E501",    # Line too long (92 > 88)
    "ERA001",  # Found commented-out code
    "FBT001",  # Boolean-typed positional argument in function definition
    "FBT002",  # Boolean default positional argument in function definition
    "PERF102", # When using only the keys of a dict use the `keys()` method
    "PERF401", # Use a list comprehension to create a transformed list
    "PIE808",  # [*] Unnecessary `start` argument in `range`
    "PLR2004", # Magic value used in comparison, consider replacing `5` with a constant variable
    "PLW2901", # `for` loop variable `cc` overwritten by assignment target
    "RET503",  # Missing explicit `return` at the end of function able to return non-`None` value
    "RUF012",  # Mutable class attributes should be annotated with `typing.ClassVar`
    "S101",    # Use of `assert` detected
    "SIM910",  # [*] Use `module_map.get(destination)` instead of `module_map.get(destination, None)`
    "SLF001",  # Private member accessed: `_card_value`
    "T201",    # `print` found
]

extend-safe-fixes = [
    "TCH003", # Move standard library import `collections.abc.Iterable` into a type-checking block
]
